version: '3'

services:
  server:
    build: ./
    ports:
      - "8000:8000"

  es:
    image: elasticsearch:7.9.0
    environment:
      - "discovery.type=single-node"
    ports:
    - "9200:9200"

  logstash:
    image: logstash:7.7.0
    ports:
      - "5959"
    depends_on:
      - es